name: Build

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: python -m pip install nox

      - name: update module files
        run: nox -s compile

      - name: generate .po files
        run: nox -s i18n

      - name: push the files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: l18n_main_cron
          create_branch: true
          commit_message: Automatic compilation update
          push_options: "--force"

      - name: Run the Action
        uses: devops-infra/action-pull-request@v0.5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: l18_main_branch
          target_branch: main
